language: node_js
node_js:
- "6"
- "6.1"
- "5.11"
- "0.6"
- "iojs"
script:
- npm install -g git+https://github.com/obscurerichard/emojipacks.git#env-config
#- emojipacks
env:
  global:
    secure: bY1G6r6wh8079JJQ76Ypkqu370CsMCaGXOLk9aRH0Xnm8e8e+2UyEGk/dmgFDZ+fhAW3ysSSZXquyYVx5n7ilrkR2Zy6VG5n8a8Lfn5M2Xp7T1f8biR+TKO+XYsBam8L9Wh6sL5oqH4U0iA8uccokE2L2UM7YHaVn+D1gvlxd5DA6XB3PIyj9pQLpRh7L6Sogdu762nSgv42X7uJU4MyWzR9/rqnqXHP1VxlyxoCy77rlkyss1rCqzRro52g5VRiSzYf9CT2YWtEI5vf+Ik+BfEhtwWIIz0H9PzwRLN/A65G0DMIVCggVemJMu94BJa2joTNFtFZE5GTGEAUsArqz0ikzr7hmS3x1E+BTOhk4YuyWrgj8lXgQcGLibocOyMXCw/3NiiOJxMT6LgjffFovWyUhAzUsXGbL4ET6UaKfeXOzIa3brkNrOjvwaChxIlqjchhtSgGqdrnRNXmtX3UO0PsNxXaeOKBbAc1+fTTECyn9txi7aKMoMgoqJ6s+U4O0705VLIv8b7TQAGRaMsqjTFLjFx5JnQ1ImMjabx0Df4+fTG/nN0Osnp/EYDMx3OD9pNKztLZn8wXQqXQlkTSLfTh/6xiO4qznPCVxJjkNyCOxzw1pk9CmuTIgbS8R+7OUXb2gUqXxK+7Hk1BVj2K2hGCz6gX+jAxu+Vo9K+zGcQ=
